detectors:
  DataClump:
    exclude:
      # In order to extract code into smaller methods, and use data in
      # a functional way that doesn't assign it to the state of an object,
      # modules dealing with an API like Terminal::Table need to pass around
      # similar data to different methods, resulting in what reek sees as a
      # data clump.  This is prevalent in the Report module as it uses data in
      # a functional way, so exclude it from this check.
      - SurveyTool::CLI::Report
  DuplicateMethodCall:
    exclude:
      # NOTE: This is due to the OptionParser syntax
      - SurveyTool::CLI::OptionParser#option_parser
      # NOTE: This is due to the Terminal::Table syntax
      - SurveyTool::CLI::Report#survey_headers
  TooManyStatements:
    # NOTE: After attempted refactorings, I've decided that it's either not
    # really possible to make the following methods shorter, or making them
    # shorter will impact readability.
    exclude:
      - SurveyTool::CLI::OptionParser#fetch_filepaths
      - SurveyTool::CLI::OptionParser#option_parser
      - SurveyTool::SurveyParser#generate_survey
directories:
  "test/":
    # NOTE: Top-level documentation is done in the module/class files themselves,
    # so it doesn't need to be repeated for test files classes.
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      # NOTE: Reek thinks the `setup` block is a UtilityFunction,
      # so disable this check.
      enabled: false
exclude_paths:
  # NOTE: CI goes looking in the vendor directory and attempts to scan all files
  # in all gems, so make the exclusion explicit here.
  - "vendor"
